spring.application.name=achievement_tracking_application

spring.datasource.url=jdbc:mysql://localhost:3306/achievement_db
spring.datasource.username=root
spring.datasource.password=Rohan@832

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect